README.md
appveyor.yml

Sets up AppVeyor. AppVeyor was actually running already, but this time the configuration is in a file. This makes it easier if this repo is cloned or something weird happens to AppVeyor.
Also, a badge is added to the README.

Set up AppVeyor

---

config/detekt/detekt-config.yml
subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRenderer.kt
subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/Node.kt
subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRendererTest.kt

This PR adds a renderer for SCFG graph.

Add DOT graph renderer

---

subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumeratorTest.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt

Builds upon #18 
Add a mapping function from patterns to sequences, thus allowing us to identify where each pattern occurs.
Also improves some of the terminology in the `PatternDetector` class to more clearly distinguish patterns from sequences.

Count sequence occurence

---

subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumerator.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumeratorTest.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/TestNode.kt

Moves the old path enumeration algorithm to the new data structure.

Adapt path enumeration to new data structure

---

subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGeneratorTest.kt

I'll add comments at the fixes.

Implement a number of class-generator fixes

---

README.md

"Codecov" should be capitalised as "Codecov" rather than as "CodeCov".

Fix Codecov capitalisation

---

subprojects/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilter.kt
subprojects/pattern-filter/src/main/kotlin/IncompleteInitPatternFilter.kt
subprojects/pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/IncompleteInitPatternFilter.kt
subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/IncompleteInitPatternFilterTest.kt

This PR moves the PatternFilter interface to the correct package.

Move pattern filter interface to correct class

---

build.gradle
subprojects/pattern-detector/build.gradle
subprojects/pattern-filter/build.gradle
subprojects/project-compiler/build.gradle
subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
subprojects/test-generator/build.gradle
subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/TestGenerator.kt
subprojects/usage-graph-generator/build.gradle
subprojects/usage-graph-generator/gradle.properties
subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootProjectLibraryUsageGraphGenerator.kt

Removes unnecessary main methods and reorders some lines in Gradle files.

Remove main methods

---

src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
subprojects/pattern-detector/build.gradle
subprojects/pattern-detector/gradle.properties
subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorAndSootComparatorTest.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorHelper.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/TestNodeComparator.kt

Integerate the tagginator into the prefix span algorithm.
Now the structure of the prefix is taken into account when building sequences.

Prefix span and tagginator integrator

---

modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedSootComparator.kt
modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestableGenerator.kt
modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/IntegrationTest.kt
modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/jimple/IncompleteInitPatternFilter.kt

This PR  changes JimpleNode's general Soot unit to a more specific Jimple statement.

Change JimpleNode's unit to a statement

---

src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt

Builds on top of many open PRs, review only "Separate pipeline and cli" and newer
__
This PR adds a new `Pipeline` class that performs the execution of all pipeline steps and brings all recent changes together.

 Separate pipeline and cli

---

modules/common/src/main/kotlin/org/cafejojo/schaapi/common/TestGenerator.kt
modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt

Fixes #87 by using the `File` solution on both ends.

Change TestGenerator interface output to File

---

modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt

This allows it to resolve classes transitively.

Pass whole-program option to Soot

---

modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/library/LibraryException.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/library/Object1.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/AnnotationTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ArrayListAndLambdaTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/StaticTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ThrowTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/TryCatchTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfBothUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfFalseUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfNoEndTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfNoUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfTrueUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/switchconditional/SwitchDefaultUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/switchconditional/SwitchNoUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/switchconditional/SwitchOneUseTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt

This PR fixes a few small bugs and adds integration tests for the LUG.

Add integration tests for LUG

---

modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/LoopContinueTest.java
modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt

This PR adds two integration tests for the UGG pipeline step: One for the `Loop` scenario (which was already included in the repository as a `.java` file, but not tested yet) and one for the `LoopContinue` scenario. I've also included a fix for an issue in the handling of the latter scenario (averting a [StackOverflow](http://stackoverflow.com) exception).

Add loop integration tests

---

modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaJarProject.kt
modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaMavenProject.kt

Change if-checks to requires in project classes

---

gradle.properties

Makes the builds somewhat faster.

Enable parallel tests in Gradle

---

modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt

Adds `-DskipTests=true` option to maven invocation.

Skip maven tests while compiling a project

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt

The `Pipeline` now expects two compilers: one for the library and one for the users.

The Lord of the Projects: The Two Compilers

---

modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaProject.kt
modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt

IntelliJ inspections gave a few warnings. I fixed them.

Fix a small number of IntelliJ inspection warnings

---

README.md

Updates the mail address in `README.md` to use our new fancy domain 😊

Update mail address in README.md

---

modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt

Disables Evosuite dependencies in generated tests.

Disable Evosuite dependencies in generated tests

---

modules/pipeline/junit-test-runner/build.gradle
modules/pipeline/junit-test-runner/gradle.properties
modules/pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/pipeline/testrunner/junit/TestRunner.kt
modules/pipeline/junit-test-runner/src/test/java/org/cafejojo/schaapi/pipeline/testrunner/junit/test/AnotherSimpleTest.java
modules/pipeline/junit-test-runner/src/test/java/org/cafejojo/schaapi/pipeline/testrunner/junit/test/EmptyTest.java
modules/pipeline/junit-test-runner/src/test/java/org/cafejojo/schaapi/pipeline/testrunner/junit/test/SimpleTest.java
modules/pipeline/junit-test-runner/src/test/kotlin/org/cafejojo/schaapi/pipeline/testrunner/junit/TestRunnerTest.kt
modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/TestRunner.kt
settings.gradle

Implements and tests the `TestRunner`, which takes a collection of JUnit 4 tests and executes the tests within them.

Add JUnit 4 test runner

---

build.gradle
gradle.properties
modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt

Add Dokka task to Gadle

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt

Smoothen the pipeline

---

README.md

Add GitHub miner to README.md

---

README.md

See [here](https://github.com/cafejojo/schaapi/blob/readme-junit-runner/README.md) for a demo

Add JUnit test runner to README.md

---

README.md

See [here](https://github.com/cafejojo/schaapi/blob/readme-spam/README.md) for a demo

Add SPAM stage implementation to README

---

README.md

Add CCSpan to README.md

---

modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGeneratorTest.kt

Remove unused imports in AppKeyGenerator and test

---

modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt

Inverts the conditions in `pathContainsSequence` to make them easier to understand.

Improve readability of `pathContainsSequence`

---

modules/github-test-reporter/build.gradle
modules/github-test-reporter/gradle.properties
modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/CheckSuiteEvent.kt
modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/WebHookReceiver.kt
modules/web/build.gradle
modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt

This PR adds support for receiving web hooks from GitHub, specifically the `check_suite` web hook.

Add GitHub web hook receiver

---

modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt

Implements and tests the `CustomEqualsList` class.

Custom equals list

---

modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt

Caches the supports calculated during CCSpan.
Review only commit `Cache the supports calculated during CCSpan`.

Cache the supports calculated during CCSpan

---

modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilter.kt
modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilterTest.kt

Adds a filter for recursive goto statements.

Filter recursive goto statements

---

modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
modules/models/src/main/kotlin/org/cafejojo/schaapi/models/Node.kt

Adds a `copy` method to `Node`s.

Add copy method to `Node`s

---

modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompiler.kt
modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt

Use brace syntax for logging where possible

---

README.md

For some reason, that step was missing from the README. I've added it.

Add project compiler step to README

---

modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt

Removes all compilation warnings.

Remove all compilation warnings

---

modules/validation-pipeline/ci-job/build.gradle
modules/validation-pipeline/ci-job/gradle.properties
modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt

Add CIJob with downloading and zip extraction

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt
modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt

Next to reducing overall unit size (from 21.45 to 21.15 SLOC per method), this also attempts to bring functions to the same abstraction level, moving out parts handling lower-level abstractions to helper methods.

Refactor long methods into smaller helper methods

---

modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitorTest.kt

Add support for some miscellaneous Value classes

---

modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobCompletedEvent.kt

This PR fixes two things suggested in previous review comments.

CI Job: Small fixes

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanPatternDetector.kt
modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectorySearchOptions.kt
modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMinerTest.kt
modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompiler.kt
modules/mining-pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompilerTest.kt
modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompilerTest.kt
modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanPatternDetector.kt
modules/mining-pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/CCSpanJimpleNodeIntegrationTest.kt
modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamPatternDetector.kt
modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt

Renames classes with the same name to make it easier to navigate between and recognise them.

Collision rename

---

modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt

Correct capitalization of Maven in log message

---

modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/IntegrationTest.kt
modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/Properties.kt
modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/CheckSuiteEvent.kt
modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/CIJobException.kt
modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobCompletedEvent.kt
modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobFailedEvent.kt
modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobSucceededEvent.kt
modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobSuccessfulEvent.kt

We will now also fire an event when the execution was not successful.

 Fire failed events after unsuccessful CI job runs

---

modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt

I noticed this while debugging and thought it was kind of weird.

Use range instead of creating a new list

---

modules/application/build.gradle

Adds a task to build the mining pipeline fat JAR.

Add task to build mining pipeline fat JAR

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt

Write library compilation output to logger

---

modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/CIJobCompletedListener.kt

Adds a disclaimer that indicates that the results of Schaapi may not be accurate.

Add accuracy disclaimer to test results

---

README.md
modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt

Allow skipping of compilation of user projects

---

modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMinerTest.kt

Adds a test by @gandreadis that was added to #336 after the PR had been merged.

Add test for hidden file exclusion

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt

This PR puts all flavor options in a map and based on the map decides whether a flavor is valid. If it's not we display an error message containing the flavors that are valid.

Clarify missing flavor argument message

---

README.md
modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt

This PR adds a list of the possible library types to the option description.

List possible library types in command line options

---

modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt

As opposed to making it an argument for the run() function.

Make libraryProject an argument for the MiningPipeline class

---

modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt

I was running Schaapi and for some reason there was no more output. I had no idea why it stopped, and the last logger message did not indicate that it had started doing something.
This PR changes a number of things during the mining process:
* Parallelises the directory miner
* Parallelises the version verifier
* Shows feedback in stdout and the logs on when downloading and verification start and end
* Fixes typos and inconsistencies in messages

Improve feedback during the mining process

---

modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompiler.kt
modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt

Adds a whole bunch of debug log statements to the program. I'm sure there are many more points where it might be useful, but currently these statements seem to be the most urgent.

More debug logs
