- build.gradle
- gradle.properties
- src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
- src/test/kotlin/org/cafejojo/schaapi/SchaapiTest.kt
- subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
- subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/UsageGraphGenerator.kt
Configures [Spek](http://spekframework.org/) and [ktlint](https://ktlint.github.io/).
Spek was configured in 057748d. The setup uses Spek's own JUnit engine to find the tests, and uses the default Jupiter engine to run the tests. The commit also contains a number of tests to show that it works.
ktlint was configured in c47f5d7. The setup uses [Spotless](https://github.com/diffplug/spotless), which is a general tool for linters. The reason that Spotless was used is that its Gradle plugin looks way more developed and maintained than ktlint's own (unofficial) plugins.
ktlint enforces the Kotlin style guide. You can configure IntelliJ to conform to this style using the following instructions:
ktlint has two tasks: `spotlessCheck` and `spotlessApply`. The former checks that the code conforms …
> Tool setup

- .travis.yml
- appveyor.yml
- build.gradle
- config/detekt/detekt-config.yml
- gradle.properties
- gradle/detekt.gradle
- src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
- subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/InstructionGrouper.kt
- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/UsageGraphGenerator.kt
Adds [Detekt](https://github.com/arturbosch/detekt/) to the project.
There's a number of peculiarities with Detekt, which initially made it hard to configure. Those issues have been resolved or hacked around.
* Detekts stuff!
* A number of rules has been ignored specifically for tests. This configuration happens in `/config/detekt/detekt-config.yml`.
* I have resolved a number of Detekt/Codacy issues that have been here since the beginning.
* Detekt **fails** on Windows unless the cache directory is set somewhere outside of the project. To work around this, always run Detekt with a relocated cache: `gradle detektCheck  --project-cache-dir=../schaapi-cache`. This extra argument should not be necessary on Unix. Yes, this also means that you will get an annoying `schaapi-cache` directory as …
> Set up Detekt

- README.md
The current AppVeyor README badge shows the status of any branch (the latest build). Instead, the status of `master` should be shown, specifically.
> Show master status in AppVeyor Badge

- subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
- subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
For finding frequent (sub)sequences the PrefixSpan algorithm by Pei et al. (2004) is used. The algorithm uses the 'divide and conquer' principle, and is partially inspired by the FP-tree structure used to mine sets of unordered items.
During each iteration, a new prefix is generated based on the current prefix and  nodes observed to be frequent in the set of paths. If this prefix is observed in the set of paths it is added to the set of frequent sequences. 
After this, all suffixes of sequences which start with this prefix are then mined recursively, with the suffix of a sequence being everything that follows said prefix. This improves upon the a priori method by foregoing the need to generate candidate sequences during each iteration. A pseudocode representation is given below.
``` …
```
> Add first version of Prefix Space Algorithm

- subprojects/pattern-detector/build.gradle
- subprojects/usage-graph-generator/build.gradle
- subprojects/usage-graph-generator/gradle.properties
- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilter.kt
- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilter.kt
- subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilterTest.kt
- subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilterTest.kt
This PR allows to filters Soot statements based on library usage.
It covers all known and expected statements and values, except for `if`s and `switch`es. These will be added it a future PR.
At the moment `isLibraryClass` in the `ValueFilter` is based on a hardcoded string, this will change once #23 is available to use.
> Add statement and value filters

- README.md
This is a very important PR! /s
It changes the style of the badges to be larger and more square. I think it makes it easier to read because the original buttons were too small. You can see a live example of this style [here](https://github.com/cafejojo/schaapi/blob/readme-badge-style/README.md).
<sup>It just looks cool so merge it OK?</sup>
> Use `for-the-badge` style for Shields.io badges

- README.md
This one is even more important than [the last one](https://github.com/cafejojo/schaapi/pull/28). Sadly, the README still doesn't have blockchain.
There's a live version [here](https://github.com/cafejojo/schaapi/blob/66e402337cbf54d176a093b34eb4c5a75c54464e/README.md).
> ➕ ❤️ 2️⃣  📝

- subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
My own global `JAVA_HOME` environment variable was not set properly, which is how I came across this issue. Because setting that variable is not essential to a Java installation, I don't believe we should require our users to have it set, seeing as the rest of our program runs fine without it. This PR fixes this by retrieving the value from a system property and setting it in the invokation request.
This PR also enables 'batch mode' in the maven install invocation, which is more appropriate for our situation (see [this SO question](https://stackoverflow.com/questions/25896081/what-is-the-diffrence-between-interactive-and-batch-mode-in-maven)).
> Explicitly set JAVA_HOME in Maven project compilation

- subprojects/test-generator/build.gradle
- subprojects/test-generator/gradle.properties
- subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassWriter.kt
- subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/SootClassWriterTest.kt
The class takes an output base directory as property and creates the right package structure within that base directory for each function call (based on the fully qualified name of the class).
Also, I think I won the record for the highest number of `class`es in a schaapi PR title. 🏆
> Add a class for writing SootClasses to .class files

- subprojects/common/src/main/kotlin/org/cafejojo/schaapi/common/JavaProject.kt
- subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
- subprojects/project-compiler/src/test/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProjectTest.kt
- subprojects/project-compiler/src/test/kotlin/org/cafejojo/schaapi/projectcompiler/MavenInstallerTest.kt
Rather than working in a directory `test` in the project's root, the `project-compiler` tests now use temporary file structures using `Files.createTempDirectory` to work in. Because directory names are now randomly generated, there is also no chance of accidentally working with the files from a previous run, and ~~the clean-up is done (or rather, _should_ be done) by the OS automatically~~ the clean-up is done manually because the OS does not do it automatically.
Additionally, this PR fixes a bug where it a `JavaMavenProject` would always look for Maven in the default directory.
There are some other test classes that also work in a `test` directory (or something similarly named), but I did not change those because they also use test-compiled classes and I want to work on those in a …
> Use OS temporary dirs to store SUT files in

- subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunner.kt
Adds an `InputStream` parameter to the `EvoSuite` constructor that is used to write EvoSuite's `errorStream` to.
Additionally:
* The behaviour of reading a stream and writing it to a parameter has been extracted into a helper method.
* The continuation indent has been changed from 8 to 4, as is required according to the the ktlint setup (refer to the Wiki article).
> Add parameter to write EvoSuite errors to

- README.md
Also fixes the inconsistency between the two build badge captions.
See [here](https://github.com/cafejojo/schaapi/blob/readme-badge-logos/README.md) for a live demo.
> Add CI logos to build status badges

- settings.gradle
- subprojects/common/src/main/kotlin/PatternFilter.kt
- subprojects/pattern-filter/build.gradle
- subprojects/pattern-filter/gradle.properties
- subprojects/pattern-filter/src/main/kotlin/IncompleteInitPatternFilter.kt
- subprojects/pattern-filter/src/test/kotlin/IncompleteInitPatternFilterTest.kt
(the filter itself is complete 😉)
This PR adds a filter to filter out patterns with incomplete initializations of objects.
It also adds a general interface for these kind of filters.
> Add incomplete-init-pattern filter

- subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunner.kt
- subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
The continuation of #47, providing another set of bug fixes found during manual integration tests.
Also, it renames the variable `classPath` to `classpath` in the `EvoSuiteRunner`.
> More Soot class generator fixes

- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootNode.kt
- subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedSootComparator.kt
- subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootNodeTest.kt
- subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedSootComparatorStructureTest.kt
Add `equals` and `hashcode` methods to `SootNode`, which means better encapsulation.
Two `SootNodes` are considered equal iff:
* Their respective `Unit` classes are the same
* The values of the operation are the same, meaning
* The amount of values are identical
* The types of the values are identical at their respective positions
Hashcodes are generated using the sum of the hashcodes of the respective types, times the index.
During the writing of this I discovered that there is a possible bug in the current implementation of the equals. Namely, the `getValues` does not recursively traverse statements, meaning that nested statements are taken as-is and not decomposed. I'm not sure if this is intended behaviour but I thought that I'd mention it.
> Move equals to SootNode class

- subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
Check the actual value rather than the box that contains the value.
Also use the actual identifier value rather than a toString of the value.
> Fix unbound variables check

- .editorconfig
- subprojects/project-compiler/src/test/resources/Project/dependencies-classes/src/main/java/org/cafejojo/schaapi/test/MyClass.java
- subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunnerTest.kt
- subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRendererTest.kt
Adds an `.editorconfig` file (a cross-editor config for basic code style configurations) and fixes a number of small left-over code style violations that somehow slipped through.
> Add .editorconfig and fix code style violations

- src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
- subprojects/pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/IncompleteInitPatternFilter.kt
- subprojects/pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/LengthPatternFilter.kt
- subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/IncompleteInitPatternFilterTest.kt
- subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/LengthPatternFilterTest.kt
- subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/TestNode.kt
Add a pattern filter which retains only patterns that have a certain minimum length. By default, a pattern should have at least length 2.
Also changes the `IncompletePatternFilter` to a `class` instead of an `object`. This was done for the following reasons:
* Singletons in general are ugly
* Some filters might have paramters, such as the new `LengthPatternFilter`, and as such for consistency they should ideally all be classes
* It more closely coincides with the project structure. Comparators are also `classes`
> Add length pattern filter

- modules/common/src/main/kotlin/org/cafejojo/schaapi/common/Pattern.kt
- modules/common/src/main/kotlin/org/cafejojo/schaapi/common/TestGenerator.kt
- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
- modules/pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGeneratorTest.kt
- src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
This PR adds a `TestGenerator` interface and moves the logic for writing testables and generating evosuite tests to its own class within the test generation module.
See Mattermost for reasoning behind not splitting testable writing and test generation in two modules.
> Add interface for test generation and move test generation logic away from Schaapi class

- modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilter.kt
- modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilterRule.kt
- modules/common/src/test/kotlin/org/cafejojo/schaapi/common/PatternFilterTest.kt
- modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/jimple/IncompleteInitPatternFilterRule.kt
- modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/jimple/LengthPatternFilterRule.kt
- modules/pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/jimple/IncompleteInitPatternFilterRuleTest.kt
- modules/pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/jimple/LengthPatternFilterRuleTest.kt
- src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
This PR restructures the pattern filters. The `jimple-pattern-filter` module now contains rules for filtering and the actual filtering is performed in a new `PatternFilter` class. The logic for filtering is (because of that) removed from the `Schaapi` class.
> Restructure pattern filters

- src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
I removed these for the following reasons:
* `inline` is an optimization, but I don't think it matters much and the function is only called 4 times, so any type of optimization won't do much. I'd rather have one keyword less than pay a 0.0001ms penalty on a process that takes a minute anyway. (The compiler might just inline the function itself actually)
* `infix` is hip and all the cool kids use it, but the infix notation is not used here so there isn't really a reason to use it I believe.
> Remove inline infix in Pipeline

- .gitignore
Now that everything has been moved to `modules`, the `.gitignore` should also be updated to ignore the `build` folder in `modules` rather than `subprojects`. That is exactly what this PR does.
> Ignore build folder in `modules` folder

- src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
Fixes #66.
The issue was that the `Class::getResource` method returns a `URL`, which automatically escapes certain characters. Therefore, this was only really an issue in the smoke test itself. I have changed the helper method `getResourcePath` to decode the characters that were encoded by `URL`.
> Unescape escaped characters in paths in smoke test

- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
- modules/pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/EvoSuiteRunnerTest.kt
This rename aims to prevent confusing the functionality of this class with the TestGenerator interface (which this class does not implement).
Fixes #88
> Rename EvoSuiteTestGenerator to EvoSuiteRunner

- modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinder.kt
- modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinderAndSootComparatorTest.kt
- modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinderHelper.kt
- modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinderTest.kt
Uses interface from #77
Some extra tests to test the integration of the prefix span algorithm with the `GeneralizedSootNodeComparator`. 
The tests themselves also uncovered a bug where only projected paths were used to construct a new projected database instead of using all the paths.
> Add integration tests for PrefixSpan and SootNodeComparator

- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedNodeComparator.kt
> Rename `getValues()` to `getTopLevelValues()`

- build.gradle
- modules/application/build.gradle
- modules/pipeline/java-maven-project-compiler/build.gradle
- modules/pipeline/jimple-evosuite-test-generator/build.gradle
- modules/pipeline/jimple-library-usage-graph-generator/build.gradle
- modules/pipeline/jimple-pattern-filter/build.gradle
- modules/pipeline/prefix-span-pattern-detector/build.gradle
- settings.gradle
The module names now correspond to the directory structure. For example, `:jimple-pattern-filter` has now been moved to `:pipeline:jimple-pattern-filter`.
> Categorise modules into submodules in Gradle

- README.md
Because "contributors" is not a name.
Yay, 100th PR!
> Uncapitalise "contributors" in README.md

- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/IfNoEndTest.java
- modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
This PR fixes an issue where no common end statement can be found.
We now just ignore this case, because this can only occur when a true/false branch has no successors. In this case it must contain a return or throw statement, and these cases we want to keep the branches.
> Fix issue where no common end statement could be found

- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/DfsIterator.kt
The `DFSIterator` previously checked for equality defined by the `equals` method implementation. In implementations such as the `JimpleNode`, however, this leads to structurally equal nodes being seen as 'visited', even though they are in fact other instances. This led to statement sequences being cut short in iteration, such as the one below (with line 1 and 2 being structurally equal):
```
int x = new LibraryClass().libraryFoo();
int y = new LibraryClass().libraryFoo();
return x;
```
> Check for references instead for equality

- gradle/integration-tests.gradle
- modules/pipeline/prefix-span-pattern-detector/build.gradle
An extension on the work added in #106, this PR extracts the integration-test specific Gradle configuration to a separate file. Simply write the following in your `build.gradle` to enable integration tests for that module:
```groovy
apply from: "$rootDir/gradle/integration-tests.gradle"
```
> Move integration test config to separate file

- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/AbstractClassTest.java
- modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/InterfaceTest.java
- modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/PartiallyAbstractClassTest.java
- modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
The current UGG implementation crashes on non-concrete methods (abstract or interface declarations) with a `RuntimeException`. This PR fixes this and adds two test cases to the module integration test suite to demonstrate this.
> Add tests for abstract methods in UGG module

- gradle/wrapper/gradle-wrapper.properties
They weren't sorted in alphabetical order before. They are now. :)
> Sort properties in Gradle wrapper properties file

- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorValueTest.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
* Adds a `getValues` function in `JimpleNode` that recursively finds _all_ `Value`s in the node.
* Changes the `generalizedValuesAreEqual` function to use `getValues` rather than `getTopLevelValues`.
* Adds tests for both functions.
> Recursive type checking

- modules/models/jimple-library-usage-graph/build.gradle
- modules/pipeline/jimple-evosuite-test-generator/build.gradle
- modules/pipeline/jimple-library-usage-graph-generator/build.gradle
- modules/pipeline/jimple-pattern-filter/build.gradle
- modules/pipeline/prefix-span-pattern-detector/build.gradle
Fixes #95.
By simply excluding `slf4j-simple` as a transitive dependency via Soot, there are no more errors when determining the binder. The transitive dependency has been removed from Soot a few minutes ago in https://github.com/Sable/soot/pull/949, but this fix is not the ~sable~ stable release yet.
> Exclude transitive dependency on slf4j-simple

- modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
Instead of doing `setPomFile(getPomFile())` I thought it would be nice to use the actual POM file of the project :wink:. (bug introduced after moving the compilation process out of `JavaMavenProject`)
> Use correct POM file in project compiler

- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/EmptyPatternTest.java
- modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
This PR:
* Filters LUGs with only returns
* Fixes assertions in the LUG integration test
* Changes `cfg` to `lug` in the integration test
> Filter empty LUGs

- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/application/src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
Rather than always using `;` to separate the paths to the user projects, the CLI will now use the OS's default path separator character.
> Use OS path separator to separate user projects

- modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PathEnumerator.kt
- modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PathEnumeratorTest.kt
Previously, this code failed when no sink nodes could be found. This PR changes this behavior to instead select the last node of the iterated list of nodes, to accommodate scenarios found in real projects.
> Change behavior of connectLeavesToExitNode

- build.gradle
- modules/application/src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
Enables Gradle exception logging.
Before | After
:---:|:---:
> Gradle failure messages

- modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinder.kt
I was not a huge fan of the code of this method (because of the for loops and stuff), so I refactored it a bit to be more kotlin-y. In 'theory' it should act exactly the same as the old implementation.
> Refactor pathContainsSequence method

- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
- modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathEnumeratorTest.kt
- modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PatternDetector.kt
This move will allow us to reuse it in other algorithmic implementations, without copying it.
> Move PathEnumerator to models module

- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfReturnsTest.java
- modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
This PR filters out non library return/throw statements that were retained by the value filter.
> Filter out non-library returns in branches

- modules/web/build.gradle
- modules/web/gradle.properties
- modules/web/src/main/kotlin/org/cafejojo/schaapi/web/HomeController.kt
- modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt
- modules/web/src/test/kotlin/org/cafejojo/schaapi/web/HomeTest.kt
- settings.gradle
This PR adds Spring in a separate web module.
The controllers for the web application will be part of relevant modules (e.g. a module for reporting to developers can define its own endpoints).
For testing I had to switch back to JUnit, since there's no nice and stable to way to test Spring apps with Spek, see issue 50 on https://github.com/spekframework/spek.
> Set up Web module using Spring

- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaJarProject.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaProject.kt
- modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
- modules/pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompilerTest.kt
- modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
- modules/pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompilerTest.kt
- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/TestGenerator.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/Helpers.kt
The `java` package inside the `java-maven-project` module is redundant because the name of the module already specifies that no other languages will be supported. Therefore, the classes in the `java` package have been moved up one level.
> Move Java projects out of `java` package

- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GithubProjectDownloader.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
- modules/pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GithubProjectDownloaderTest.kt
Two fixes:
1. Fixes the capitalisation of "GitHub" (from "Github" to "GitHub")
2. Renames `*SeachOptions` to `*SearchOptions`
> Seach options typo fix

- build.gradle
- gradle/tests/test-configuration-generator.gradle
This PR fixes the missing coverage through the following two changes:
1. Instead of putting all the execution data in one file, there is now a separate file for each module.
2. `jacocoTestReport` now depends on `moduleIntegrationTest`
Strictly speaking, I think only the second change was necessary, but the first one is also nice.
> Include module-integration test coverage in report

- modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
- modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMiner.kt
- modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/SearchOptions.kt
- modules/pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMinerTest.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GitHubProjectDownloader.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
- modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
- modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/LibraryUsageGraphGenerator.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/PatternFilterRule.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectCompiler.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectMiner.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/SearchOptions.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/TestGenerator.kt
Now Project generics are also passed to the pipeline. One for the library project type and one for the user library type.
`in` and `out` keywords are used where necessary:
* `in` means that it may take as input a subtype of the generic that it has inferred. For instance, if the inferred generic is `JavaProject`, it may also take as input `JavaMavenProject`.
* `out` means that it may give as output any supertype of the inferred generic. For instance, if the inferred generic is `JavaMavenProject`, it may also give as output a `JavaProject`.
For instance, in the pipeline:
1. `JavaMavenCompiler` compiles the library project and outputs a `JavaMavenProject`
2. `JavaJarCompiler` compiles the user projects and outputs a `JavaJarProject`
Now, The `LibraryUsageGraphGenerator` would normally, …
> Add Project Generics to Pipeline

- modules/application/build.gradle
- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
- modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
- modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/DirectorySearchOptions.kt
- modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMiner.kt
- modules/pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMinerTest.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectMiner.kt
- modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/SearchOptions.kt
Builds upon #161. See [here](https://github.com/cafejojo/schaapi/pull/167/files/af9d31ad68f021c49e0f5a92f90122915fd6c9ef..4eae4b64bfb0164d812dbf903e35e4576af5754c) for easy review.
* Use the directory project miner in the `CommandLineInterface`
* Remove unecessary generic type parameter from `SearchOptions`
* Use generics to ensure `SearchOptions` type is compatible with the `ProjectMiner`
> Add Project Miner to Pipeline

- README.md
- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
The semantics of the user projects argument was changed in an earlier PR without changing the corresponding CLI command name.
> Rename 'user_dirs' argument to 'user_base_dir'

- appveyor.yml
@gandreadis and I suspected that the flakiness of AppVeyor was the result of the parallel builds. To verify this, I forked the Schaapi repo and [ran the `master` build 20 times on AppVeyor](https://ci.appveyor.com/project/FWDekker/schaapi/history): 10 times with parallel builds and 10 times without. With parallel builds enabled, 3 builds failed. Without parallel builds, 0 builds failed. Therefore, it is likely that the parallellism caused AppVeyor to fail.
This PR disables the parallel builds for AppVeyor.
> Disable parallel builds in AppVeyor

- modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/PatternDetector.kt
- modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/SPAM.kt
- modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/Spam.kt
- modules/pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/SPAMTest.kt
- modules/pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/SpamTest.kt
Rename the confusing `allPath` variable and its derivatives to `sequence` and its derivates:
* `sequence` and its derivatives are used to denote sequences, which more closely coincides with literature
* `patterns` and its derivates are used to denote the output of the algorithm, to more closely coincide with the name of the pipeline
Also rename `FrequentSequenceFinder` to `PrefixSpan` to make clear it uses the PrefixSpan algorithm.
* Make the class internal as it is not used elsewhere.
> Rename FrequentSequenceFinder class in spam module to Spam

- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/DotGraphRenderer.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
- modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
* Make the `companion object` of `BranchStatementFilter` private, as it is not used elsewhere
* Make filters internal, as these are not part of the interface
* Make extension function in `ControlFlowGraphGenerator` private, including the accompanying Exception, as it used only by this class.
* Make `DotGraphRendered` internal, as it is not part of the interface
> Make usagegraphgenerator module non-interface classes internal

- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassWriter.kt
- modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
Classes that do not implement the interface should not be public. Therefore, these have been made internal. Their functions have also been made internal, and some have been made private.
The `ValueIsNotLocalException` has been made internal as this should also not be part of the interface, it is only thrown.
> Decrease visibility of classes in Jimple EvoSuite package

- modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GitHubProjectDownloader.kt
- modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
- modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
`GithubProjectDownloader` is not part of the interface, and should therefore not be public. It is now internal.
> Decrease visibility of GitHub project miner package

- modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/ProjectMinerTest.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GithubProjectDownloaderTest.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/TestProject.kt
- modules/mining-pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompilerTest.kt
- modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/MavenInstallerTest.kt
- modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompilerTest.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassWriterTest.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvoSuiteRunnerTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/DotGraphRendererTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/IncompleteInitPatternFilterRuleTest.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/LengthPatternFilterRuleTest.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanTest.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/TestNodeComparator.kt
- modules/mining-pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamTest.kt
- modules/mining-pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/TestNodeComparator.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorStructureTest.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorValueTest.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootMockFactory.kt
- modules/validation-pipeline/junit-test-runner/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunnerTest.kt
This was done:
* To decrease visibility of tests. They should not be visible outside the module
* There is no need for mutiple instances of tests, so they are all `object`s. This also follows the Spek recommendations.
> Make All Tests Internal Objects

- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Moves `o.c.s.Pipeline` to `o.c.s.miningpipeline.MiningPipeline`.
> Move `Pipeline` to `miningpipeline.MiningPipeline`

- README.md
- appveyor.yml
Commits only modifying the README.md shouldn't be built. AppVeyor supports such exclusion rules! Rephrases a passage in the README.md to test this.
Travis unfortunately [does not support this](https://github.com/travis-ci/travis-ci/issues/6301).
> Skip AppVeyor builds modifying only the README

- detekt.yml
- modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
- modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
- modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
- modules/validation-pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunner.kt
No idea how they got into `master`, but they did, so here are my fixes for them. I agree with the rule preferring 'to' expressions over 'Pair' statements - feel free to disagree, however.
I did not agree with the 'MandatoryBracesIfStatements' rule. Seeing as we don't consistently follow it in the rest of the codebase, either, I turned it off in `detekt.yml`.
Note: This build will likely fail until #200 is merged, as there still remains a failing Windows-test on this branch.
> Fix Detekt rule violations

- modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
- modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGeneratorTest.kt
The path previously had a leading slash (`/D:/...`) which caused a test failure on Windows setups.
Note: PR builds here will likely fail until #199 (concerning Detekt fixes) is merged.
Also, PR #200 🎉😄
> Fix key path on Windows in AppKeyGeneratorTest

- .gitignore
Because of [this bug in IntelliJ](https://youtrack.jetbrains.com/issue/IDEA-116898), some users have the problem that IntelliJ automatically changes their Gradle wrapper properties and JAR, which makes these files constantly visible in `git status`, which is annoying.
This PR makes git ignore those files.
> Ignore Gradle wrapper jar and properties

- modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanTest.kt
- modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
This PR:
* adapts CCSpan to make use of the PathUtil frequent node finder (which provides a speedup over the current implementation)
* fixes an issue in the PathUtil finder that caused erroneously high support counts in cases where the same element appeared multiple times in the same path
* adds an optimalization for the support check, traversing only sequences with appropriate length
> Speed up frequent singleton detection

- modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
Converts two streaming calls in CCSpan to parallel streaming calls. Not all in this class could be converted, due to dependencies between steps.
In doing so, the size of the node count types was changed to 'Long' (instead of 'Int'), as the Java streaming API returns that format.
> Parallelize streaming statements in CCSpan

- modules/application/src/main/resources/logback.xml
Configures the logger to report only messages of levels `WARN` and up.
> Logger config

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Overcomes the bug where the `target` of an `GotoStmt`, `IfStmt`, or `SwitchStmt` has been filtered out in the LUG or the pattern detector while a reference to it remains in another statement, making the body invalid.
> Replace missing targets with returns

- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/IncompleteInitPatternFilterRule.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/LengthPatternFilterRule.kt
What the title says. This makes it easier to see what happens in the pipeline. I'll be adding more log messages to the other pipeline steps soon so we can get a better view of what is happening as well.
Log messages which are not in the `MiningPipeline`, and are in the pipeline steps themselves should usually be `debug`, and sometimes `warn` or `error`, but rarely if ever `info`.
> Add log messages to PatternFilterRules

- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
- modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathEnumeratorTest.kt
The current `PathEnumerator` is bugged because it is unable to detect loop blocks, and will therefore copy entire for loops including their condition (which is useless). This PR works around that issue by no longer unrolling loops, simply leaving the loops in the path.
> Stop unrolling loops in the `PathEnumerator`

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
These should be ignored and not added as locals. Field references to the library should be persisted (they are not 'unbound variables'), and array references should not be added as complete references (e.g. a[2]) but only as base objects (a), which are in the use-def boxes, anyways.
> Filter instance and array references in ClassGenerator

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
When a local is assigned twice in a method body, the `ClassGenerator` will also try to add it twice as a local to the body, which is not possible in Soot.
The first commit in this PR adds a test that replicates the issue, and the second commit fixes the issue by preventing the addition of duplicate locals.
> Fix duplicate locals

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
While #217 made the `ClassGenerator` filter instance field refs, this PR will also make it filter static field refs. 
The first commit (after the commits from #219) adds a test that replicates the buggy behavior, and the second commits fixes it.
> Filter more field refs

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
As attempted in #214  and #218, nodes should be duplicated before being used to generate bytecode. However, simply duplicating the nodes is not sufficient, as they often have links between them. These also need to be updated, which is what this PR does.
> Make copies of nodes in each sequence, while maintaining referential integrity

- README.md
- modules/application/build.gradle
- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/GithubMiningCommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/MissingArgumentException.kt
- modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Add option to the command line to switch between pipelines. It is not the most elegant solution I admit but in the interest of time I think it's best to do it this way for the time being.
Few things of note:
* The GitHub mining pipeline requires the library be a jar, the directory mining pipeline requires the library be a maven project
* I'm not sure whether the command line arguments are too vague. It might be an idea to have multiple arguments where you for instance specify `library-type` (`jar`/`maven`) `language`, etc. For now however that felt slightly overkill.
> Multiple pipelines

- README.md
- modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
At the moment we take a very random sample of GitHub projects and mine these for patterns. A problem however with this approach is that a lot of the projects downloaded seem to be incomplete hobby projects, with very few files and next to no patterns.
It might therefore be necessary to at times limit ourselves to more relevant projects. To facilitate this the option to sort by stars and watchers has been added. Before, a single query was done to search for `pom` files on GitHub which contain a dependency on said library. Afterwards, the results were trimmed to the `maxProjects` before in turn querying GitHub for the projects which contain said `pom` files. Now however,  after the first query a query has to be done for each code file to get the stargazer and/or watcher count of the …
> Add GitHub sorting options

- modules/validation-pipeline/github-test-reporter/build.gradle
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporter.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/GitHubApi.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/Properties.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/events/CheckSuiteEvent.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/events/InstallationEvent.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/events/Shared.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/AppKeyGeneratorTest.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporterTest.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/IntegrationTest.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
- modules/validation-pipeline/github-test-reporter/src/test/resources/fixtures/github/installation_created_webhook.resp
- modules/validation-pipeline/github-test-reporter/src/test/resources/fixtures/github/installation_deleted_webhook.resp
- modules/validation-pipeline/github-test-reporter/src/test/resources/githubtestreporter.properties
- modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt
This PR adds processing of installation web hooks.
For each new installation a directory will be created on the file system in which tests for the installation repos can be stored.
In a future PR we will also receive web hooks for adding/removing repositories from an already installed installation.
> Receive installation web hooks

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
#220 added duplication of statement sequences. While working correctly for jump statements pointing outside the unit chain, loop constructs are incorrectly handled. The current implementation fails to maintain referential integrity for these kinds of scenarios. This PR adds an (initially failing) test for this behavior and proposes a fix for it.
Credits to @FWDekker for spotting this one!
> Fix jimple sequence duplication

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GithubProjectDownloaderTest.kt
See issue #229 
In addition to this, project files are now propely extracted. Before, projects contained a directory within which denoted the master branch which within contained the project. This is now directly extracted.
Before:
```
projects
|- project0
|- master
|-files...
|- project1
|- master
|-files...
```
After:
```
projects
|- project0
|-files...
|- project1
|-files...
```
> Properly delete zip files

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Currently, the `ClassGenerator` wrongly thinks that a variable is initialised if it is set to itself in the first assignment where it appears. For example, it will think that the variable `r9` is correctly initialised in the following two snippets and will conclude that it does not need a method parameter:
* ```r9 = r9```
* ```r9 = r9.doSomething()```
The issue is that the `ClassGenerator` looks at the use and def boxes of a `Statement` in no particular order, which means that it may look at the definition before looking at the usage. When this happens, it will gladly add the variable to the list of defined variables before moving on to the usage.
This PR fixes the issue by making the `ClassGenerator` look at the usages before looking at the definitions. As an extra, the …
> Recursive definition fix

- build.gradle
- modules/application/build.gradle
- modules/mining-pipeline/jimple-evosuite-test-generator/build.gradle
- modules/mining-pipeline/jimple-library-usage-graph-generator/build.gradle
- modules/mining-pipeline/jimple-pattern-filter/build.gradle
- modules/mining-pipeline/prefix-span-pattern-detector/build.gradle
- modules/models/jimple-library-usage-graph/build.gradle
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
PR #226 tried to fix the `equivTo` and `equivHashCode` of Soot's `Local`s by changing the behaviour when `equivTo` was called on a `JimpleNode` that contained a `Local`, but this fix did not prevent the incorrect implementation from being called when a `Local` was inside another `Value`. Therefore, PR #226 did not fix the issue of duplicate patterns because Soot thinks two `Local` are not equivalent (even though they are).  Since the changes from #226 are not longer necessary, they have been removed in this PR. The regression tests added by that PR are still in place, of course.
This issue has been reported to Soot (see Sable/soot#953) and a PR has been opened by @gandreadis to fix this issue (Sable/soot#954), but it has not been merged yet. Because the issue has to be solved quickly in …
> Fix equivalence of `Local`s

- modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/EmptyLoopPatternFilterRule.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/EmptyLoopPatternFilterRuleTest.kt
In the process of filtering out library usages, it is common to see a `goto` statement pointing backwards in a ⛓ of statements. Methods were this produces an empty (likely infinite) :repeat: should be filtered out, to avoid the 🔥 of infinite 🔁.
> Add empty loop filter

- build.gradle
For some reason, Gradle did not discover JUnit tests. This PR adds the JUnit Jupiter test engine to discover those tests. Now we finally have coverage of the web module.
> Add JUnit test engine

- modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompiler.kt
- modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/Helpers.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaJarProject.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaProject.kt
Using a `List` to store the names of the classes in a `Project` is great and all, but it doesn't scale. I just ran the pipeline on a project with >30k classes, and the JLUG took an exceptionally long time to build the usage graphs; 30% of this time was spent on determining whether a given class belonged to the library project.
Instead, all class names (and also the dependencies, because why not?) are now stored in a `Set`, which means that `contains` is now O(1) instead of O(n). Insertion will now take O(log n) instead of O(1), but I estimate that we will have exponentially more containment checks than insertions.
> Speed up class name containment checks in Projects

- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
Fixes a few things:
* Uses Apache-CLI's own method for getting the default values of options rather than a custom-built one. (My mistake, oops.)
* Renames `libraryMaven` and `libraryJar` to `libraryProject` because there is no such thing as "a Maven".
* Sorts variables in both CLI implementations to make them more consistent.
* Makes the program return a non-zero exit code if the program did not execute successfully.
> Use default default default

- build.gradle
- modules/application/build.gradle
- modules/mining-pipeline/jimple-evosuite-test-generator/build.gradle
- modules/mining-pipeline/jimple-library-usage-graph-generator/build.gradle
- modules/mining-pipeline/jimple-pattern-filter/build.gradle
- modules/mining-pipeline/prefix-span-pattern-detector/build.gradle
- modules/models/jimple-library-usage-graph/build.gradle
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitorTest.kt
Adds a custom visitor that recursively visits the expressions contained within a `Value`. I originally wrote this class in one of my attempts described in #233, but I found that I could also use it when writing a filter to remove patterns that did not have enough library usages (which ~~will be featured in an upcoming PR~~ is used in #235).
Reviewer's note: Only review 11fb9ac.
> Jimple value visitor

- README.md
The project mining step was called "Project Mining", but this was not consistent with the other steps, which follow the pattern "[verb] [noun]".
> Fix project mining step name in README

- modules/validation-pipeline/ci-job/build.gradle
- modules/validation-pipeline/ci-job/gradle.properties
- modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
- modules/validation-pipeline/github-test-reporter/build.gradle
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
- modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/ValidateRequestReceivedEvent.kt
- modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/ValidationRequestReceivedEvent.kt
- modules/web/build.gradle
- modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt
- settings.gradle
This PR fires an event when a web hook to start a check run is received.
It also adds a new `ci-job` module, in which the actual ci run will be executed. It will be responsible of creating a new thread for itself as well.
> Add validation events

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
Consider the following statement:
`UserClass.STATIC = libraryClassInstance()`
The `ValueFilter` will think that this statement exclusively uses the library, even though the LHS does not. This is because it does not check the usages in the LHS. This PR makes it check the LHS. Simple as that.
> Do not retain non-library usages on LHS

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilterTest.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaJarProject.kt
- modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
- modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
Consistently use `@Suppress` instead of using `@SuppressWarnings` in some places and `@Suppress` in others.
> Consistently use `@Suppress`

- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitorTest.kt
Upgrades the `JimpleValueVisitor` to
* allow different overrides for the different `Ref` classes
* allow different overrides for the different `Immediate` classes
* allow different overrides for the different `AnyNewExpr` classes
* allow overrides for unrecognised classes at different levels (e.g. one override for an unrecognised `Value`, another for an unrecognised `Ref`, and yet another for an unrecognised `FieldRef`)
This is the first step towards fixing the annoying bugs with excessive filtering in the `StatementFilter`.
> Upgrade `JimpleValueVisitor` to support more `Value`s

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/Helpers.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitorTest.kt
The `ValueFilter` should be doing three things:
1. Filtering _out_ particular classes of `Value`s
2. Filtering _out_ `Value`s that use something from a user's own code (because we cannot use these statements)
3. Filtering _out_ `Value`s that do not use the library.
Previously, the `ValueFilter` did 1 and 2, but I was unable to implement 3 because it is incompatible with 2. This is because 2 is a universal check of absence ("for all not"), while 3 is an existential check of presence ("any").
Therefore, I have split the `ValueFilter` into three separate filters, each filter performing one of these three steps. I thought it would be easiest to do this using the `JimpleValueVisitor`, so I did.
> Filter separation

- modules/mining-pipeline/ccspan-pattern-detector/build.gradle
- modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
- modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/NodeSequenceUtil.kt
This PR fixes two bugs:
1. It makes the pattern detector deterministic again by removing a `parallelStream()` where the order of execution was important (because the `GeneralizedNodeComparator` ~is~ was not thread-safe).
2. It makes sure that the `NodeSequenceUtil`'s `sequenceContainsSubSequence` uses the correct order of arguments when calling `GeneralizedNodeComparator`'s `satisfies` method.
The second bug is also explicitly covered by a regression test.
> Pattern detector fix

- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporter.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/CustomHttpClient.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/FuelConfiguration.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/GitHubApi.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/JsonObjectBuilder.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/CheckSuiteEvent.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/InstallationEvent.kt
- modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/Shared.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporterTest.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/Helpers.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/IntegrationTest.kt
- modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
Improves the structure of the GitHub test reporter a bit.
It now looks as follows:
> Restructure GitHub test reporter

- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
While #255 separated the `ValueFilter` into three parts, this should also be done in the `StatementFilter` because it should retain a `DefinitionStmt` even if only one of the two uses the library.
> Retain `DefinitionStmt` if either uses library

- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootNameEquivalenceChanger.kt
When the `clone` method is called on a `NameIgnoringJimpleLocal` it should return a `NameIgnoringJimpleLocal` instead of a `JimpleLocal`.
> Ensure that clone of custom `JimpleLocal` is custom `JimpleLocal`

- modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
- modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
When `subList` is called on a `CustomEqualsList`, the sub-list should also be a `CustomEqualsList`.
> Custom equals sub-list

- modules/application/src/module-integration-test/resources/user/a/pom.xml
- modules/application/src/module-integration-test/resources/user/a/src/main/java/org/cafejojo/schaapi/test/user/a/UserClass.java
- modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
- modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompilerTest.kt
This turned out not to be necessary for the pipeline (analyzing the compiled project for LUGs still works without it), and was quite time and space intensive. The smoke test has been modified to include an external dependency in one of the user projects, do demonstrate that the mining pipeline still works.
> Remove copy-dependencies step in Maven compiler

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Because values may be initialized only in one branch of a method CFG, they may be uninitialised when called upon. This change initializes all locals that are not parameters, at the beginning of the method (after all identity statements).
Fixes #272
> Always initialize local variables in the ClassGenerator

- modules/application/src/main/resources/logback.xml
I believe that the default choice should provide the user with enough output to get an understanding of what's going on in the tool at the moment, which the `info` level provides. I suggest we make this level the default.
> Set default log level to 'info'

- modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
- modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
- modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanPatternDetector.kt
- modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanPatternDetector.kt
- modules/mining-pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/CCSpanJimpleNodeIntegrationTest.kt
- modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamPatternDetector.kt
- modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimplePathEnumerator.kt
- modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimplePathEnumeratorTest.kt
- modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
- modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathEnumeratorTest.kt
Given the following pseudo-Jimple code:
```
a()
IF condition GOTO c()
b()
GOTO d()
c()
d()
```
the current implementation of the path enumerator will produce the following paths:
```
a()
IF condition GOTO c()
b()
GOTO d()
d()
```
```
a()
IF condition GOTO c()
c()
d()
```
The former pattern is incorrect because it has a `GOTO` to an instruction that is not in the path, and the latter pattern is incorrect because the `IF` does not actually branch because it always goes to `c()`.
This PR introduces a Jimple-aware pattern detector that performs post-processing on the paths produced by the `PathEnumerator` to produce the following paths instead:
```
a()
IF condition GOTO d()
b()
GOTO d()
d()
```
```
a()
IF !condition GOTO d()
c()
d()
```
> Jimple-aware enumerator

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/Processor.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessor.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/Helpers.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessorTest.kt
If a `ReturnStmt` returns a type from a user project, it should be filtered out.
Additionally, `IfStmt`s should be filtered out if they use the user project, except that this would significantly reduce the amount of paths accessible, so instead these conditions are changed with a random one. Something similar happens to `SwitchStmt`s.
> Filter out user-project usages from all kinds of statements

- build.gradle
- gradle.properties
~Hopefully~ fixes issues with Jacoco's calculation of coverage in Kotlin.
| Before | After |
|---|---|
| ![Low coverage](https://user-images.githubusercontent.com/13442533/41849939-18e5d726-7883-11e8-80e3-e69487bdf33e.png) | ![High coverage](https://user-images.githubusercontent.com/13442533/41849943-1c86b116-7883-11e8-9d17-5c5e80358b11.png) |
> Use snapshot release of Jacoco

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
If a method returns `null`, the current `ClassGenerator` will set its return type to `null_type`. That's not good. This PR makes the `ClassGenerator` set the return type to `java.lang.Object` instead.
> Make return type `Object` if `null` is returned

- gradle.properties
Bumps the version number of Schaapi to 1.0.0-RC1. The plan is to create a (pre-)release after this PR has been merged.
> Bump version number to 1.0.0-RC1

- modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/githubapi/JsonObjectBuilder.kt
Suppresses a warning about an unused parameter, because it is "used" to give calls to this method more context.
We will have no more warnings after this PR has been merged.
> Suppress warning about unused `of` parameter

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/library/LibrarySupplier.java
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/library/Object1.java
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/users/LambdaClassConstantTest.java
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/users/LambdaTest.java
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/users/LambdaUsageTest.java
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
Supersedes #295 and arguably a variation on #294.
Fixes the bug with `ClassConstant`s in lambdas. The changes are as follows:
* All `ClassConstant`s that start with a `(` are lambda types and are therefore filtered out. Soot just can't handle them.
* A `ClassConstant` is retained if the class it uses is a library type. At this point, it cannot contain a `(` because then it would already have been filtered out by the previous point.
* A `ClassConstant` is removed if the class it uses is a user project type. Again, it cannot contain a `(`.
> Filter lambdas

- codecov.yml
For some reason Codecov started displaying build stati on PRs and made the PR fail if the coverage didn't increase enough. This PR disables that again.
> Do not require Codecov checks to pass

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleUsageGraphGeneratorIntegrationTest.kt
- modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobIntegrationTest.kt
- modules/validation-pipeline/github-interactor/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/GitHubInteractorIntegrationTest.kt
Renames all `IntegrationTest` classes to make it easier to distinguish between them.
> Distinguish integration test classes

- modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
- modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
- modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobIntegrationTest.kt
- modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
Due to a design flaw in the previous version, running the CI job was not async. This meant that the connection from GitHub to our application remained open for a long time while posting a new web hook.
> Make CI job truly asynchronous

- codecov.yml
#300 didn't exactly work, so here's another attempt. From now on, Codecov will pass as long as we still have 10% coverage afterwards. I deliberately didn't choose 0% or 1% because you know how it is with edge cases.
> Practically ignore Codecov checks

- modules/application/src/main/resources/logback.xml
Log messages are now written to a file as well. The name of the file contains the time the program was started, and the file is stored in the same directory as the JAR.
> Log log messages to file as well

- modules/application/src/main/resources/logback.xml
- modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
All messages are still logged to file.
All information should now be conveyed to the user using progress bars (see #301).
If the user wants to see detailed info they shoud look at the log files themselves.
> Only log error messages to the console

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Before, the input stream was opened in the `downloadAndSaveProject` method, which did not catch `IOExceptions`. These however were thrown if an input stream could not be opened.
Now, the input stream is opened directly inside the `getInputStream` function, previously the `getConnection` function, which to me makes more sense. 
From what I've read online, it seems that closing this input stream is sufficient for releasing the underlying resources of the connection, meaning that is not necessary to also close the connection itself.
> Handle IOException when opening InputStream to download GitHub project

- README.md
This should make the origin of the name/acronym clearer to first-time readers.
🐑
> Emphasise Schaapi acronym in README.md

- modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
No matter what was passed to the if above, the output handler still
received a logger meaning that there was always output. This behaviour
has been fixed.
> Remove incorrect logger argument

- modules/application/src/main/resources/logback.xml
Changes the logger configuration such that they can be configured independently. Before, changing the `level=` in either logger didn't actually affect the log levels for some reason. With this PR, the console logger's log level can be changed by changing the threshold of the filter.
> Fix appender configurability

- codecov.yml
#300 and #310 didn't fix the Codecov after all, so here's my third attempt.
Turns out I forgot a `:` somewhere in the YAML, so obviously it didn't work. Additionally, I set the YAML to allow coverage drops of up to 100% without causing the Codecov check to fail.
---
I added a commit that lowered the coverage, and Codecov still passed! (I've removed the commit afterwards.)
> Really fix the Codecov yaml this time

- README.md
Fixes three things in the README:
1. Adds instructions for running as a JAR.
2. Usage instructions for Gradle now actually work!
3. CLI options have been updated.
[Click here to view the new README](https://github.com/cafejojo/schaapi/blob/readme-usage-instructions/README.md)
> Update usage instructions in README

- README.md
The program is actually expecting a first argument (the directory flavor). Since this is not handled by our CMD library, it doesn't show up in the generated argument help menu. Still, we should add it to our README instructions, because I had to manually dive into the code to discover this (which normal users shouldn't have to do).
> Add mining flavor argument to CMD instructions

- README.md
As described in our [thesis](https://repository.tudelft.nl/islandora/object/uuid:cca5e4ea-3d00-4ae3-877a-b302829e7f08?collection=education), there are a lot of ethical complications when notifying users. Also, since it is not included in our implementation it does not make sense to mention it as a pipeline step in the README.
> Remove user notification pipeline step from README

- detekt.yml
For some reason, Detekt enabled the newly added `UnnecessaryApply` rule even though we didn't update Detekt. I have suppressed the `UnnecessaryApply` rule globally because it gives a warning for _every_ `apply` found in the codebase because it _might_ not be useful, which makes the rule extremely useless.
> Disable Detekt's UnnecessaryApply rule

- detekt.yml
- modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanPatternDetector.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/CsvWriter.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/LibraryUsageGraphGenerator.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/PatternDetector.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/PatternFilter.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/ProjectMiner.kt
A small code quality PR.
* Change List to Iterable in CsvWriter, so the project still compiles
* Use the count() method in MiningPipeline instead of size property
The reasoning is that in a pipeline we only wish that we are given
objects which are iterable. Whether the underlying structure is a list
or not is not relevant.
> Change List to Iterable in all Interfaces

- modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
This is mainly for the `.DS_store` macOS file, which should not be considered by our tool.
> Exclude hidden files from directory pipeline

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
Prevents Schaapi from getting stuck if Soot finds a class constant which is not supported.
Instead of causing the whole pipeline to crash the exception is logged as an error, and said filter returns `false`, meaning that the passed `Value` does not contain a use of the `libraryProject`.
> Handle Invalid Class Constants

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
Before, we would replace invalid targets on the list of duplicate statements, which was a duplicate of the active body and was thrown away afterwards.
The issue was that there was no guarantee that this list of statements ended with a return statement. Therefore, if the last statement was an `if` statement with an invalid target, we replaced its body with a
reference to the last statement. This would be the `if` statement itself creating an empty while loop, instead of the intended behaviour which was a reference to the `return` or `returnvoid` of the method body.
Now, we do the same but on the active body on the statement. This is guaranteed to have a return statement as the method `addReturnStatement` was called before.
In short, it seems that we no longer have empty while loops in the …
> Replace Invalid Targets in Actual Active Method Body

- modules/mining-pipeline/gradle.properties
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Fixes #327 by simply updating the loading bar dependency.
<sub>Also, I secretly fixed a capitalisation error, which is **totally** out of scope for this PR but I had to because AppVeyor is so slow and I don't want to wait for it to finish building before another PR can be merged.</sub>
> Fix logger errors

- README.md
I felt that the current README version was lacking explanations for what the pipeline flavors and library types actually mean and what possible values they have, so I added them.
> Improve flavor and library type explanations in README

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
In the JLUGGenerator, some nested it constructs made implicit references to shadowed `it` variables (causing warnings). I have replaced these instances in outer scopes with explicit names to prevent these namespace collisions.
> Fix implicit references to 'it' in JLUGGenerator

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
On my macOS setup, the smoke test failed, due to EvoSuite not finding 'tools.jar'. After some debugging, I found out that this had to do with the JAVA_HOME variable not being visible to EvoSuite. I have fixed this by setting this variable explicitly for the subprocess that we launch for EvoSuite.
> Fix issue with EvoSuite JAVA_HOME setup

- README.md
- modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
As discussed IRL, this should help clear things up for the user if EvoSuite takes a long time to finish.
> Enable EvoSuite output by default

- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
- modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMinerTest.kt
- modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/githubapi/CustomHttpClient.kt
For some reason Detekt is now failing on `SwallowedException` even though that wasn't a thing before. As a result, all new builds fail.
Where appropriate, this has been fixed.
> Work around Detekt SwallowedException errors

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
Since #355, every pattern has its own pattern class. As a result, there will be no pattern classes if there are no patterns. However, EvoSuite will exit abnormally if there are no input classes.
To fix this, a method-less pattern class will be created if there are no patterns. To warn users of the fact that there are no patterns, a warning is logged.
> Output empty class if no patterns were found

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
If unzipping of a user project's code fails, parts of the zip may already have been extracted. If these directories are later used using the directory miner, Schaapi may crash when trying to read the half-extracted project.
This PR deletes the directory to which the zip is extracted if unzipping fails.
> Delete faulty project files

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
Sometimes, a control flow graph of `JimpleNode`s contains an `IfStmt` with only one successor. When this happens, the single successor is always the next node in the method body, so in essence the then-branch and else-branch are the same node. However, soot's built-in `getSuccsOf` method checks for duplicates when returning the list of successors, and as such will return only one node.
To resolve this, I have added a `postProcess` method that will find `IfStmt`s with only one successor, and will add this successor to the list again.
The rest of the pipeline seems to have no problem with this change.
> Prevent `IfStmt`s from having only one successor

- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
- modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
Exceptions in the library-usage graph generator are now caught so that Schaapi does not crash. Furthermore, exceptions in the retrieving of individual methods are caught at the method-level, so that other methods in the same class will still have a LUG.
> Catch LUG exceptions

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
While unzipping projects obtained during the GitHub mining process, unpacking will fail on Windows if the zip contains a directory with a colon in its name. This PR prevents that from happening by telling the unpacking library to replace colons with underscores while unpacking, similar to how Windows' native unzipper and 7zip handle colons.
> Replace `:` with `_` during unpacking

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Rather than extracting the archives downloaded by the GitHub miner and then moving the output up one directory, this PR simplifies the process so that the extraction happen to the correct directory right away.
This has two consequences:
1. It prevents a (probably Windows-only) bug where you get an access denied exception while moving the files up one directory.
2. The extraction process is faster because you don't need to move all those files.
> Simplify GitHub project extraction process

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
- modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
While projects are being downloaded by the GitHub downloader, users receive no feedback on what's happening. This PR adds a loading bar for the duration of the downloading and unzipping of user projects.
To do this, the downloader class now takes a `Stream` instead of a simple `List`. The parallellity of this stream is determined by the supplier of the stream.
Additionally,
* loading bars are now redirected to `System.out` instead of `System.err`,
* output directories now have a digest rather than a number appended,
* a shared `createProgressBarBuilder` function is added to create a consistent layout for progress bars throughout the application,
* the method `getURl` was renamed to `getUrl`, and
* fixes an error in the tests that resulted in two temporary directories not being deleted.
> Add loading bar for downloading user projects

- README.md
- modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
- modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
This PR parallelises EvoSuite. This parallelisation is disabled unless the `--test_generator_parallel` option is given. This option requires that `--test_generator_disable_output` is also given. Parallel EvoSuite ran 3 times as fast on my machine with an artificial project.
Because EvoSuite will always generate tests for all classes in a directory, the pattern classes had to be separated by directory. Therefore, instead of having two patterns in `patterns/`, one pattern will be in `patterns/pattern0/` and the other in `patterns/pattern1/`. This will make navigation harder, but I could not find another way to tell EvoSuite to run an instance per pattern.
Additionally, progress bars have been added for writing patterns to classes and for generating tests, respectively. The progress bar for …
> Parallelise evosuite

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
For some reason, the `_schaapi_project_dependencies.txt` was placed in the `output/project/output/project/` directory on a Linux machine. The issue was resolved by giving Maven an absolute path to output to.
> Output dependency tree on absolute path

- README.md
- modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
Users can now give the `--delete_output_dir` option to delete the output directory before running the pipeline.
> Allow cleaning output directory before running

- modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
Currently, EvoSuite used a VFS (and a VNET) for mocking IO-related functionality in its tests. However, due to a discrepancy between the runtime behavior of EvoSuite tests and their search-time environment, this caused tests using those mock objects to fail when executed. This PR adds two options to the EvoSuiteRunner which disable the usage of virtualized file systems and network.
> Turn off EvoSuite VFS usage

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Sometimes the GitHub project downloader would fail to download a project because it could not find the zip. Turns out this happens when the project in question does not have a `master` branch. ~~To prevent this from happening, the downloader now downloads the default branch instead.~~ Edit: Because of a bug in the GitHub API library we're using (cf. kohsuke/github-api#494), the default branch cannot currently be obtained. Therefore, the workaround is to just use the `master` branch if it exists, and to reject the user project otherwise.
> Skip projects without master branch

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
This PR resolves what is currently the only compilation warning in the codebase by making the type requirement in the GitHub miner less strict. After all, the miner doesn't care whether the code is written in Java, it just wants it to be a Maven project so that it can find the `pom.xml`.
> Loosen strict type requirement in miner

- modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/build.gradle
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessor.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/Helpers.kt
- modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessorTest.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/InsufficientLibraryUsageFilterRule.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/BranchStatementFilter.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/Filter.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/RecursiveGotoFilter.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/StatementFilter.kt
- modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/ValueFilter.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/InsufficientLibraryUsageFilterRuleTest.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/Helpers.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/RecursiveGotoFilterTest.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/StatementFilterTest.kt
- modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/ValueFilterTest.kt
In the InsufficientLibraryUsageFilterRule filter. This fix ensures that we also include patterns which only have static calls the library, which would otherwise have been filtered away.
Furthermore:
* When accumulating visits, return true iff either is true
> If a Statement is a Static Invoke, Check Method Reference Declaring Class

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
The `URL` constructor may throw an `IOException`, for example when the URL is malformed. These exceptions should be caught.
> Catch exceptions while constructing URLs

- modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
According to [this comment on StackOverflow](https://stackoverflow.com/questions/5784778/#comment95983536_26869885), `skipTests` will only skip execution of tests, while `maven.test.skip` will skip both compilation and execution. Since we don't look at test code, we should skip that step to speed up the process.
> Skip compilation of tests

- modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompiler.kt
Prevents the `Jar project at {path} is empty.` message from being displayed when the jar in question is not actually empty. The issue was that the check for the message checked the wrong variable (`classes` instead of `classNames`) 🤦‍♂️ 
I also reformatted the code because it took me way too long to spot the `with(project)`.
> Resolve false-positive "empty jar" warning

- README.md
- modules/application/build.gradle
- modules/application/src/main/resources/logback.xml
Users can now enable debug output in the log file by setting the `log.level` system property to `debug`. We barely have any debug log statements at the moment, but that will be the subject of a future PR.
> Allow enabling debug output on command line

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
This change requires a switch from `dependency:tree` to `dependency:list`. This command produces a slightly different output, which is why the output file parsing has slightly been changed.
> Don't 'compute' transitive dependencies in version verifier

- modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
When the `GitHubProjectMiner` has found a project, it will then call run the `projectPacker` on that project. By default, the `projectPacker` is the constructor of the `JavaMavenProject` class. If the project does not contain a `pom.xml`, this constructor will throw an `IllegalArgumentException`, which will kill the entire pipeline.
To solve this, the `projectPacker` function has been changed to verify that there is a `pom.xml` before actually packing the project.
> Check for presence of pom.xml before packing

- modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
ZipUtil throws an `IllegalArgumentException` when it encounters a non-UTF-8 character in a filename, which causes the entire pipeline to crash. Simply catching this exception makes the pipeline more resilient.
> Catch encoding-related exceptions during unzipping
